# This is the default configuration and should be filled with production environment values

spring:
   # Spring App Name
   application.name: henge
   
   # Spring Active Profiles   
   profiles.active: dev,flatfile_local,setmapping
   
   # Need to utilize jersey as a filter instead of a servlet so we can host static content
   jersey.type: filter

#Tomcat Configuration
multipart.max-file-size: 2Mb

server:
   # Set the webapp context root
   contextPath: /henge

# Swagger configuration properties
swagger:
   api.version: 1.0
   schemes: http,https
   base.path: /henge
   resource.package: com.kenzan.henge.resource
   scan: true
   domain: localhost
   port: 8080

# Cache
cache.expiration.minutes: 60

# Text encoding throughout all repository implementations
text.encoding: utf-8 

scope:
   # Scope precedence configuration used in evaluating properties and resolving matches from queries to VersionSets
   precedence.configuration: env;env+region;env+region+stack;subenv;application

   # String to represent the application name in the scope keys
   application.name.key: application

#Eureka Client Configuration - Eureka Server
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# Cassandra database configuration
cassandra:
   host: localhost
   port: 9042
   
# Security Credentials
security:
   user: user
   password: user   

